---
- name: download golang package
  get_url:
    url: "https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz"
    dest: /opt/go1.4.2.linux-amd64.tar.gz
  register: package
  tags:
    - common

- name: extract golang package
  unarchive:
    src: /opt/go1.4.2.linux-amd64.tar.gz
    dest: /opt
    copy: no
  when: package.changed
  tags:
    - common

- name: set golang GOROOT environment variable
  lineinfile:
    line: "export GOROOT=/opt/go"
    regexp: "^export GOROOT="
    dest: /root/.bashrc
    state: present
  tags:
    - common

- name: add golang to PATH environment variable
  lineinfile:
    line: "export PATH=/opt/go/bin:$PATH"
    regexp: "^export PATH=/opt/go/bin"
    dest: /root/.bashrc
    state: present
  tags:
    - common
