---
- name: install nginx
  yum:
    name: "http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.8.1-1.el7.ngx.x86_64.rpm"
    state: present
  tags:
    - consul

- name: update nginx config
  sudo: yes
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - consul

- name: allow consul http port in selinux
  command: semanage port -a -t http_port_t  -p tcp 8500
  ignore_errors: true
  tags:
    - consul

- name: configure consul proxy
  sudo: yes
  template:
    src: etc/nginx/conf.d/consul.conf.j2
    dest: /etc/nginx/conf.d/consul.conf
  notify:
    - restart nginx
  tags:
    - consul

- name: remove default nginx configuration
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  notify:
    - restart nginx
  tags:
    - consul

- name: remove default ssl nginx configuration
  file:
    path: "/etc/nginx/conf.d/example_ssl.conf"
    state: absent
  notify:
    - restart nginx
  tags:
    - consul
