---
- name: install nginx
  yum:
    name: "http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.9.5-1.el7.ngx.x86_64.rpm"
    state: present
  tags:
    - terminal

- name: remove default nginx configuration
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  tags:
    - terminal

- name: create directory for streams
  sudo: yes
  file:
    path: /etc/nginx/stream.d
    state: directory
  tags:
    - terminal

- name: replace default config file
  sudo: yes
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - terminal

- name: add dcos lb
  sudo: yes
  template:
    src: etc/nginx/stream.d/dcos.conf
    dest: /etc/nginx/stream.d/dcos.conf
  notify:
    - restart nginx
  tags:
    - terminal
