---
- name: install consul-template
  yum:
    name: "https://bintray.com/artifact/download/ciscocloud/rpm/consul-template-0.8.0-2.el7.centos.x86_64.rpm"
    state: present
  tags:
    - consul-template

- name: deploy consul config
  copy:
    src: consul.cfg
    dest: /etc/consul-template/config.d
  notify:
    - reload consul-template
  tags:
    - consul-template

- name: enable consul-template
  service:
    name: consul-template
    enabled: yes
    state: started
  tags:
    - consul-template

- meta: flush_handlers
